### ISSUE TITLE
Revisit Signal Panels

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/typhos#250]
- The misc panel never shows any signals. Should it be removed from the default templates?
- `omitted` signals are currently completely omitted from the display, as they should be intuitively. Should this be the case even in the detailed engineering screen?
- `read` and `hinted` signals are mingled together in the default templates. In small devices this works very well, in large devices this does not work at all. Should the `read` signals be moved to a tab?
- It's not clear if the separation between hinted and read attributes is done correctly here: https://github.com/pcdshub/typhos/blob/0837405e8d8b73227ac34eb69d2390eed85f3c65/typhos/utils.py#L99-L100 Which deserves either a fix or a clean-up

**Comment by klauer** [comment]
These are all good points that need addressing.

Just want to add: if a tab - miscellaneous or otherwise - has no signals, it should be hidden.

**Comment by klauer** [comment]
Since the time of this issue, there have been drastic changes to typhos. Let's address them one-by-one and see where we need to go from here. Adding numbers to make things easier to reference.

> (1) The misc panel never shows any signals. Should it be removed from the default templates?

It should now show 'omitted'. It's unclear if this is desirable, leading to (2).

![image](https://user-images.githubusercontent.com/5139267/81845224-236de080-9505-11ea-882a-0ab35b900e09.png)

> (2) `omitted` signals are currently completely omitted from the display, as they should be intuitively. Should this be the case even in the detailed engineering screen?

I can see arguments for/against this.  If 'omitted', I agree they seemingly shouldn't be viewed or changed - normally. I think the key here is 'normally'.

Maybe we don't include the miscellaneous panel in the screens by default, but still just allow the right-click showing or 'config menu dropdown filter' settings to allow them to show.

Or we leave it as-is. Opinions?

> (3) `read` and `hinted` signals are mingled together in the default templates. In small devices this works very well, in large devices this does not work at all. Should the `read` signals be moved to a tab?

The "flattening" nature of the default signal panel is problematic, for sure. The tree is closer to ideal for large devices now.

I can definitely see the case for the proposed layout:

    (hinted signals)
    (panel tab "read" | panel tab "configuration")

This may make smaller device usage worse. We might want to investigate this with several devices and make a decision based on that.

> (4) It's not clear if the separation between hinted and read attributes is done correctly here: https://github.com/pcdshub/typhos/blob/0837405e8d8b73227ac34eb69d2390eed85f3c65/typhos/utils.py#L99-L100 Which deserves either a fix or a clean-up

I'd like to remove this `grab_kind` thing entirely. The panel no longer uses it, but the positioner (which needs refactoring) does.

Based on the results of our upcoming discussions/decisions here, let's open up separate issues to tackle for the next release.

**Comment by ZLLentz** [comment]
For (1) and (2), I don't have a particularly strong opinion... your suggestion about leaving omitted out by default and then allowing a right-click reveal seems reasonable.

For (3), I like the read/config as panel tabs, but only because we may be losing the omitted tab and the config tab will be lonely. I don't suppose it would hurt to do some basic heuristics on the number of hinted + reads and create the panel tab for read only if there are a lot of them?

(4) is now solved by your positioner rework

And following on now that we have the tree view, we should start thinking about cases where we want a scrollable tree view below a hinted area for huge nested devices, e.g.
```
(hinted signals always visible)
(tree of read + config) [scroll bar only scrolls here]
```

... There are so many combinations and options here that it's hard to evaluate

**Comment by hhslepicka** [comment]
Here is my take on this proposal:

(1) & (2):
- Omitted should be left out with the possibility to display it. (Sometimes I find that some signals that I wish were hinted are omitted, e.g.: shaped image on Image Plugin :shrug:)

- The Miscellaneous could be displayed only if Omitted is marked to keep them separated from the rest.

(3):
- I don't believe we will have many smaller devices based on what I saw at the pcdsdevices and looking at also devices ready to play from Ophyd.
- Since the ratio of small devices to large ones is pending to large devices I would say it should take precedence on design.
- Even if it becomes a bit worst for smaller devices, I believe that the trend is for them to get templates, right?

(4) 
- `grab_kind` was always very confusing to me. I agree 100% we should remove it entirely as it would also become obsolete once we get this in https://github.com/bluesky/ophyd/issues/862.

**Comment by klauer** [comment]
Forgot to mention, `grab_kind` was already removed as of the positioner PR. I'll split this up and open up new issues based on your thoughts.

**Comment by klauer** [comment]
I think I extracted the important points here. Let me know if I missed anything.
